# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guruMatch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guruMatch.proto',
  package='guruMatchPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fguruMatch.proto\x12\x10guruMatchPackage\"e\n\x06Mentee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0e\n\x06school\x18\x05 \x01(\t\x12\x10\n\x08interest\x18\x06 \x01(\t\"?\n\x13\x43reateMenteeRequest\x12(\n\x06mentee\x18\x01 \x01(\x0b\x32\x18.guruMatchPackage.Mentee\")\n\x14\x43reateMenteeResponse\x12\x11\n\tpersisted\x18\x01 \x01(\x08\x32j\n\tGuruMatch\x12]\n\x0c\x43reateMentee\x12%.guruMatchPackage.CreateMenteeRequest\x1a&.guruMatchPackage.CreateMenteeResponseb\x06proto3'
)




_MENTEE = _descriptor.Descriptor(
  name='Mentee',
  full_name='guruMatchPackage.Mentee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='guruMatchPackage.Mentee.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='guruMatchPackage.Mentee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='guruMatchPackage.Mentee.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='guruMatchPackage.Mentee.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='school', full_name='guruMatchPackage.Mentee.school', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interest', full_name='guruMatchPackage.Mentee.interest', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=138,
)


_CREATEMENTEEREQUEST = _descriptor.Descriptor(
  name='CreateMenteeRequest',
  full_name='guruMatchPackage.CreateMenteeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mentee', full_name='guruMatchPackage.CreateMenteeRequest.mentee', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=203,
)


_CREATEMENTEERESPONSE = _descriptor.Descriptor(
  name='CreateMenteeResponse',
  full_name='guruMatchPackage.CreateMenteeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='persisted', full_name='guruMatchPackage.CreateMenteeResponse.persisted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=246,
)

_CREATEMENTEEREQUEST.fields_by_name['mentee'].message_type = _MENTEE
DESCRIPTOR.message_types_by_name['Mentee'] = _MENTEE
DESCRIPTOR.message_types_by_name['CreateMenteeRequest'] = _CREATEMENTEEREQUEST
DESCRIPTOR.message_types_by_name['CreateMenteeResponse'] = _CREATEMENTEERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mentee = _reflection.GeneratedProtocolMessageType('Mentee', (_message.Message,), {
  'DESCRIPTOR' : _MENTEE,
  '__module__' : 'guruMatch_pb2'
  # @@protoc_insertion_point(class_scope:guruMatchPackage.Mentee)
  })
_sym_db.RegisterMessage(Mentee)

CreateMenteeRequest = _reflection.GeneratedProtocolMessageType('CreateMenteeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMENTEEREQUEST,
  '__module__' : 'guruMatch_pb2'
  # @@protoc_insertion_point(class_scope:guruMatchPackage.CreateMenteeRequest)
  })
_sym_db.RegisterMessage(CreateMenteeRequest)

CreateMenteeResponse = _reflection.GeneratedProtocolMessageType('CreateMenteeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMENTEERESPONSE,
  '__module__' : 'guruMatch_pb2'
  # @@protoc_insertion_point(class_scope:guruMatchPackage.CreateMenteeResponse)
  })
_sym_db.RegisterMessage(CreateMenteeResponse)



_GURUMATCH = _descriptor.ServiceDescriptor(
  name='GuruMatch',
  full_name='guruMatchPackage.GuruMatch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=248,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateMentee',
    full_name='guruMatchPackage.GuruMatch.CreateMentee',
    index=0,
    containing_service=None,
    input_type=_CREATEMENTEEREQUEST,
    output_type=_CREATEMENTEERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GURUMATCH)

DESCRIPTOR.services_by_name['GuruMatch'] = _GURUMATCH

# @@protoc_insertion_point(module_scope)
