# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import guruMatch_pb2 as guruMatch__pb2


class GuruMatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMentee = channel.unary_unary(
                '/guruMatchPackage.GuruMatch/CreateMentee',
                request_serializer=guruMatch__pb2.CreateMenteeRequest.SerializeToString,
                response_deserializer=guruMatch__pb2.CreateMenteeResponse.FromString,
                )
        self.GetUserName = channel.unary_unary(
                '/guruMatchPackage.GuruMatch/GetUserName',
                request_serializer=guruMatch__pb2.UserID.SerializeToString,
                response_deserializer=guruMatch__pb2.GetUserNameResponse.FromString,
                )


class GuruMatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMentee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuruMatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMentee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMentee,
                    request_deserializer=guruMatch__pb2.CreateMenteeRequest.FromString,
                    response_serializer=guruMatch__pb2.CreateMenteeResponse.SerializeToString,
            ),
            'GetUserName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserName,
                    request_deserializer=guruMatch__pb2.UserID.FromString,
                    response_serializer=guruMatch__pb2.GetUserNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guruMatchPackage.GuruMatch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GuruMatch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMentee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/guruMatchPackage.GuruMatch/CreateMentee',
            guruMatch__pb2.CreateMenteeRequest.SerializeToString,
            guruMatch__pb2.CreateMenteeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/guruMatchPackage.GuruMatch/GetUserName',
            guruMatch__pb2.UserID.SerializeToString,
            guruMatch__pb2.GetUserNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
